# Generated by Django 4.2.1 on 2023-05-20 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_options_alter_todo_datecomplited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='datecomplited',
            new_name='datecompleted',
        ),
    ]
